name: Build curriculum pdf from markdown file and publish it
on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-md:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: md to html
        uses: docker://pandoc/core:3.1
        with: 
          args: -s curriculum-vitae.md -c style.css -o curriculum-vitae.html
      - name: html to pdf
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: curriculum-vitae.html
          outputFile: curriculum-vitae.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Generate tag
        uses: DanySK/semver-autotag-action@0.1.0
      - name: Release curriculum
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z ${GITHUB_TOKEN} ]]; then
            echo "No token found... unable to deploy"
            false
          else
            TAG=$(git describe --tags --exact-match HEAD)
            hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
            gh release upload "$TAG" *.pdf --clobber
          fi
