name: Build curriculum pdf from markdown file and publish it
on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-md:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install missing fonts
        run: |
          wget -O Mona_Sans.zip "https://github.com/github/mona-sans/releases/download/v1.0.1/MonaSans.zip"
          unzip -d mona_sans/ Mona_Sans.zip
          mv mona_sans /usr/share/fonts/
          fc-cache -fv
      - name: Setup Typst
        uses: typst-community/setup-typst@v3
      - name: Compile the resume
        run: typst compile resume.typ resume.pdf
      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2
        with:
          format: YYYY-MM-DD
      - name: Add a tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.current-time.outputs.formattedTime }}
      - name: Release resume
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.current-time.outputs.formattedTime }}
        run: |
          gh release create --title "Resume" $TAG resume.pdf
